version: '3.7'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    # tell n8n how to build URLs so it uses your domain
    environment:
      - DB_TYPE=sqlite
      - DB_SQLITE_VACUUM_ON_STARTUP=true

      - N8N_PROTOCOL=https
      - N8N_HOST=ai.wrldwide.agency
      - N8N_PORT=5678

      - N8N_EDITOR_BASE_URL=https://ai.wrldwide.agency/   # UI links
      - N8N_PUBLIC_API_BASE_URL=https://ai.wrldwide.agency/ # API/webhook URLs

      # (optional) Lock down with basic auth
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=youruser
      - N8N_BASIC_AUTH_PASSWORD=yourpass

    ports:
      - "5678:5678"    # Coolify will proxy 80/443 → 5678

    volumes:
      - ./n8n-data:/home/node/.n8n   # persist DB, credentials, workflow data
