version: '3.8'

services:
  n8n:
    # you can switch this to `image: your-image:tag` if you build elsewhere
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # custom n8n + ghost-plus settings
      N8N_CUSTOM_EXTENSIONS: /home/node/.n8n/custom/n8n-nodes-ghostplus
      N8N_RUNNERS_ENABLED: "true"
      # add any other N8N_ or GHOST_ env vars here
    volumes:
      - n8n_data:/home/node/.n8n
    # notice: no "ports:" mapping, just expose
    expose:
      - "5678"
    healthcheck:
      test: ["CMD-SHELL", "/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      start_period: 120s
      retries: 3

volumes:
  n8n_data:
