version: "3.8"

services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    image: n8n-ghostplus:latest     # tag as you like
    ports:
      - "5678:5678"               # container → host mapping
    environment:
      # custom extension + runners
      N8N_CUSTOM_EXTENSIONS: /home/node/.n8n/custom/n8n-nodes-ghostplus
      N8N_RUNNERS_ENABLED: "true"
      # permissions + cookies
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_SECURE_COOKIE: "false"
      # add any additional env vars here
    volumes:
      - n8n_data:/home/node/.n8n    # persistent storage
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      start_period: 120s
      retries: 3

volumes:
  n8n_data:
    # data persists across redeploys
