version: "3.8"

services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    image: n8n-ghostplus:latest       # you can tag it whatever you like
    ports:
      - "5678:5678"                   # maps container 5678 → host 5678
    environment:
      # custom extension + runners
      N8N_CUSTOM_EXTENSIONS: /home/node/.n8n/custom/n8n-nodes-ghostplus
      N8N_RUNNERS_ENABLED: "true"
      # permissions + cookies
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_SECURE_COOKIE: "false"
      # any other envs you need go here…
    volumes:
      - n8n_data:/home/node/.n8n    # persistent data
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      start_period: 120s
      retries: 3

volumes:
  n8n_data:
