version: '3.8'

services:
  n8n:
    image: tks08gskggok0w0sco88g0gg:0c0baa0b7ee1b65fceceff03d1dec38dd2f71015
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - ~/.n8n:/home/node/.n8n
    environment:
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom/n8n-nodes-ghostplus
      - N8N_RUNNERS_ENABLED=true
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - NODE_ENV=production
